# Generated by Django 3.1.3 on 2020-11-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=255)),
                ('cardType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelID', models.CharField(max_length=255)),
                ('levelDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbcID', models.CharField(max_length=255)),
                ('sbcStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('userType', models.IntegerField()),
                ('userLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_levels', to='skud_app.level')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerID', models.CharField(max_length=255)),
                ('readerType', models.CharField(max_length=255)),
                ('readerStatus', models.CharField(max_length=255)),
                ('readerSbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reared_SBCs', to='skud_app.sbc')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logID', models.CharField(max_length=255)),
                ('logDatetime', models.DateTimeField()),
                ('logAction', models.CharField(max_length=255)),
                ('logResult', models.CharField(max_length=255)),
                ('logCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='skud_app.card')),
                ('logLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='skud_app.level')),
                ('logReader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='skud_app.reader')),
                ('logSbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SBCs', to='skud_app.sbc')),
                ('logUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='skud_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='levelReader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level_readers', to='skud_app.reader'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сard_users', to='skud_app.user'),
        ),
    ]
