# Generated by Django 3.1.3 on 2020-11-12 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logLevel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='skud_app.level'),
        ),
    ]
