# Generated by Django 3.1.3 on 2020-11-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0002_auto_20201108_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logID',
        ),
    ]
