# Generated by Django 3.1.3 on 2020-11-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0003_auto_20201112_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userFIO',
            field=models.CharField(default='Dzubenko Mihail Petrovich', max_length=255),
            preserve_default=False,
        ),
    ]
