# Generated by Django 3.1.3 on 2020-11-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0004_user_userfio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='levelReader',
        ),
        migrations.AddField(
            model_name='reader',
            name='readerLevel',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='Reader_levels', to='skud_app.level'),
            preserve_default=False,
        ),
    ]
