# Generated by Django 3.1.3 on 2020-11-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userLevel',
        ),
        migrations.AddField(
            model_name='user',
            name='userLevels',
            field=models.ManyToManyField(to='skud_app.Level'),
        ),
    ]
